### PR TITLE
WIP: Latest git head 2

### PR DESCRIPTION
**Pull request by mardy**
This PR brings back the infamous QtPim update, but this time it should not bring your device into a reboot loop. :-)

However, in order to avoid that situation, it's mandatory that the following PRs get included in the same image, or the device won't be able to boot to unity8:

- https://github.com/ubports/ubuntu-ui-toolkit/pull/16
- https://github.com/ubports/history-service/pull/5
- https://github.com/ubports/telephony-service/pull/1
- https://github.com/ubports/address-book-service/pull/1
- https://github.com/ubports/buteo-sync-plugins-contacts/pull/1
- https://github.com/ubports/sync-monitor/pull/7
- https://github.com/ubports/qtorganizer5-eds/pull/3

Some are "no change rebuild"s, but others bring significant changes in order to update our components to the latest QtPim API (QtPim made some heavy API-incompatible changes, that's why all these changes are needed).
I've testes this on my device and on the `xenial_-_latestqtpim` repo, and I haven't noticed regressions; however, this is a huge change and I recommend merging it right after the OTA release, so that we have plenty of time to catch and fix regressions that might be found before the next OTA (given the depth of the changes, I'd be surprised if we don't find any!).

### CODE REVIEW

**Comment by jbruechert** [comment]
FYI I needed this patch https://salsa.debian.org/jbb-guest/ubuntu-ui-toolkit/blob/master/debian/patches/Fix-build-with-latest-qtpim.patch to make ubuntu-ui-toolkit build against the latest qtpim. Maybe it is useful for you as well.

**Comment by mardy** [comment]
Thanks, @JBBgameich! That was very useful indeed :-)

**Comment by mardy** [comment]
This change causes a crash in unity8:
```
(gdb) bt
#0  0xa5771230 in QtContacts::QContactManagerData::createEngine (this=<optimized out>, managerName=..., parameters=...) at qcontactmanager_p.cpp:142
#1  0xa57787ee in QtContacts::QContactManager::createEngine (this=this@entry=0x1e82a8, managerName=..., parameters=...) at qcontactmanager.cpp:244
#2  0xa5778978 in QtContacts::QContactManager::QContactManager (this=0x1e82a8, managerName=..., parameters=..., parent=<optimized out>) at qcontactmanager.cpp:239
#3  0xa5b150de in ContactUtils::sharedManager(QString const&) () from /usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Telephony/libtelephonyservice-qml.so
#4  0xa5ae88f4 in ContactWatcher::ContactWatcher(QObject*) () from /usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Telephony/libtelephonyservice-qml.so
#5  0xa5acd50c in void QQmlPrivate::createInto<ContactWatcher>(void*) () from /usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Telephony/libtelephonyservice-qml.so
#6  0xb6823eb4 in QQmlType::create(QObject**, void**, unsigned int) const () from /usr/lib/arm-linux-gnueabihf/libQt5Qml.so.5
#7  0xb6873c48 in QQmlObjectCreator::createInstance(int, QObject*, bool) () from /usr/lib/arm-linux-gnueabihf/libQt5Qml.so.5
#8  0xb6875164 in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) () from /usr/lib/arm-linux-gnueabihf/libQt5Qml.so.5
#9  0xb687583a in QQmlObjectCreator::setupBindings(bool) () from /usr/lib/arm-linux-gnueabihf/libQt5Qml.so.5
#10 0xb690fb68 in __bss_start__ () from /usr/lib/arm-linux-gnueabihf/libQt5Qml.so.5
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by mardy** [comment]
The crash I mentioned in the previous comment is due to an ABI incompatibility between the new QtPim and the "galera" backend used by the address book. I have fixed this (see the pull request for address-book-service) and now the phone can boot and the contacts appear in the address book.

It still looks wrong for unity8 to have a dependency on QtContacts; sooner or later we might want to address this.

**Pull request merged**
